"""Spawn :mod:`benchmarks.xbow_runner` for each pentest menu action.

Why subprocess rather than in-process? ``xbow_runner.main()`` mutates
global state in three places:

  - ``config.verbosity.mode = "verbose"`` / ``"silent"`` based on its
    own argparse flags (xbow_runner.py:559-561) — would leak into
    subsequent menu actions.
  - ``logging.basicConfig(...)`` (xbow_runner.py:570) — second call
    is a no-op, so the second action would inherit the first
    action's log config.
  - Attaches a ``LiveLogHandler`` to the root logger and installs an
    ``HttpxQuietFilter`` (xbow_runner.py:581-587) — both global,
    both accumulate.

Subprocess gives us free isolation: each menu action gets a fresh
Python interpreter, a fresh ``src.graph`` import (which re-reads
``SWARM_*`` env vars from the parent process — see
:mod:`src.cli.config_store`), and clean SIGINT propagation. ``stdio``
is inherited so the runner's native compact / verbose / silent
streaming reaches the user's terminal unchanged.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from src.cli import bench_discovery

# Project root — used as the subprocess cwd so ``uv run`` resolves the
# right venv regardless of where ``swarm`` was invoked from.
_PROJECT_ROOT = Path(__file__).resolve().parents[2]


# ---------------------------------------------------------------------------
# Public actions — one per menu item
# ---------------------------------------------------------------------------

def run_one(bench_id: str, *, pause_on_exit: bool = True) -> int:
    """Pentest one XBOW benchmark. Matches the user's original
    ``uv run python -m benchmarks.xbow_runner --bench <ID> --skip-build``.
    """
    return _spawn(
        ["--bench", bench_id, "--skip-build"],
        pause_on_exit=pause_on_exit,
    )


def run_queue(bench_ids: list[str], *, pause_on_exit: bool = True) -> int:
    """Pentest a user-built queue of benchmarks, in the given order.

    Backs the TUI's "xbow benchmark" picker, where the user queues
    benchmarks with ``r`` (1st, 2nd, 3rd …). One id collapses to the
    single-benchmark path (:func:`run_one`); two or more are written —
    in queue order — to ``benchmarks/run_queue.txt`` (gitignored) and
    handed to ``xbow_runner --list-file``, the same consecutive-run
    mechanism used by "first 5 patched" and "run all".

    ``--skip-build`` matches :func:`run_one`: the picker is for already
    built images, and the build step is cached anyway.
    """
    if not bench_ids:
        return 0
    if len(bench_ids) == 1:
        return run_one(bench_ids[0], pause_on_exit=pause_on_exit)

    list_path = _PROJECT_ROOT / "benchmarks" / "run_queue.txt"
    list_path.write_text(
        "# Generated by the `swarm` TUI run queue — line order is run order.\n"
        + "\n".join(bench_ids)
        + "\n",
        encoding="utf-8",
    )
    # ``--usage-guard``: this is a multi-benchmark sweep, so pace it against the
    # selected Codex account's 5-hour limit (waits between benches when the
    # account nears the cap). See src/cli/usage_guard.py.
    return _spawn(
        ["--list-file", str(list_path), "--skip-build", "--usage-guard"],
        pause_on_exit=pause_on_exit,
    )


def run_daily(*, silent: bool, pause_on_exit: bool = True) -> int:
    """Pentest the 15 daily benchmarks.

    ``silent=False`` matches ``--daily --resume --skip-build`` (compact
    streaming, default UX). ``silent=True`` matches
    ``--daily --resume --silent`` for overnight runs where you only
    want the final verdict per benchmark.
    """
    extra = ["--silent"] if silent else ["--skip-build"]
    return _spawn(
        ["--daily", "--resume", *extra, "--usage-guard"],
        pause_on_exit=pause_on_exit,
    )


def run_first5_patched(*, pause_on_exit: bool = True) -> int:
    """Pentest XBEN-001 to XBEN-005, applying bit-rot patches first.

    Runs ``benchmarks/patch_bitrot.sh`` as a preflight to repair the
    Dockerfiles whose upstream base images have rotted (mysql:5.7.15
    manifest, Debian buster apt 404, phantomjs gone from buster
    archive). The script is idempotent and saves originals as
    ``<file>.bitrot_orig`` so reverting is one command.

    No ``--skip-build``: the patcher just cleared each benchmark's
    ``.xben_build_done`` guard, so we *want* a fresh build with the
    patched Dockerfile. No ``--resume`` either — this is a deliberate
    re-run, must not be silently skipped if these IDs are in prior
    ``results/xbow_*.jsonl``.

    Returns the patcher's exit code if it failed (so the menu can
    report the failure clearly), otherwise the xbow_runner's.
    """
    import subprocess
    patcher = _PROJECT_ROOT / "benchmarks" / "patch_bitrot.sh"
    print(f"[first5-patched] running preflight patcher: {patcher}")
    try:
        proc = subprocess.run(
            ["bash", str(patcher)],
            cwd=str(_PROJECT_ROOT),
            check=False,
        )
        if proc.returncode != 0:
            _print_error(
                f"patch_bitrot.sh failed (rc={proc.returncode}).\n"
                "Cannot proceed to the benchmark run. Inspect the\n"
                "output above and fix or run `bash benchmarks/"
                "patch_bitrot.sh --revert` to undo any partial changes."
            )
            if pause_on_exit:
                _wait_for_enter(proc.returncode)
            return proc.returncode
    except KeyboardInterrupt:
        if pause_on_exit:
            _wait_for_enter(130)
        return 130

    list_path = _PROJECT_ROOT / "benchmarks" / "daily_5_first_patched.txt"
    return _spawn(
        ["--list-file", str(list_path), "--usage-guard"],
        pause_on_exit=pause_on_exit,
    )


def run_all(*, pause_on_exit: bool = True) -> int:
    """Pentest every XBEN-*-24 benchmark on disk (~104).

    Writes the list of IDs to ``benchmarks/all_xben_24.txt`` (cached,
    gitignored), then invokes xbow_runner with ``--list-file``. Silent
    mode is forced because 104 benchmarks × compact output = wall of
    noise; the per-benchmark verdicts in ``results/xbow_*.jsonl`` are
    where the data lives.
    """
    try:
        list_path = bench_discovery.ensure_all_list()
    except FileNotFoundError as exc:
        _print_error(str(exc))
        return 4  # distinct from xbow_runner's 0/2/3 exit codes
    return _spawn(
        ["--list-file", str(list_path), "--resume", "--silent", "--skip-build",
         "--usage-guard"],
        pause_on_exit=pause_on_exit,
    )


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _spawn(args: list[str], *, pause_on_exit: bool) -> int:
    """Run ``uv run python -m benchmarks.xbow_runner <args>``.

    ``env=os.environ`` is the default — passing it explicitly here as
    a reminder that ``SWARM_*`` overrides injected by
    :func:`config_store.load_into_env` propagate via inherited env.
    stdio is NOT captured: the runner streams to the user's terminal
    directly, and Ctrl-C is delivered to the child as SIGINT (which
    ``asyncio.run`` inside xbow_runner handles cleanly).
    """
    cmd = ["uv", "run", "python", "-m", "benchmarks.xbow_runner", *args]
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(_PROJECT_ROOT),
            env=os.environ.copy(),
            check=False,
        )
        rc = proc.returncode
    except KeyboardInterrupt:
        # User hit Ctrl-C; subprocess inherited the SIGINT and exited.
        # Treat as a clean cancellation, not a TUI crash.
        rc = 130

    if pause_on_exit:
        _wait_for_enter(rc)
    return rc


def _wait_for_enter(rc: int) -> None:
    """Pause until the user hits Enter — only when invoked from the TUI.

    Without this, the menu redraws immediately and the final run
    summary scrolls off-screen before the user can read it.
    """
    from rich.console import Console
    Console(stderr=True).print(
        f"\n[dim]Run exited with code {rc}. [enter] to return to menu…[/dim]",
        end=" ",
    )
    try:
        input()
    except (EOFError, KeyboardInterrupt):
        pass


def _print_error(message: str) -> None:
    """Render a red rich panel without crashing if rich is somehow missing."""
    try:
        from rich.console import Console
        from rich.panel import Panel
        Console(stderr=True).print(
            Panel(message, title="Cannot run", border_style="red")
        )
    except Exception:
        print(message, file=sys.stderr)
